version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/' # Location of package manifests
      schedule:
          interval: 'weekly'
      groups:
          npm-deps:
              patterns:
                  - '*'
      ignore:
          - dependency-name: 'tailwindcss'
            versions: ['>=4.0.0']
